### ISSUE TITLE
Images that fail

### ISSUE THREAD

**Issue by willwashburn** [willwashburn/FasterImage#9]
From time to time I've come across images that fail -- creating a list here to see if we can't fix them eventually

- https://www.staysafe.org/files/2018/01/unplugged.jpg

**Comment by jwbats** [comment]
I run an Amazon affiliate website, on which I use AMP4WP to generate AMP images. This plugin uses this library to determine image dimensions, so that it can display images correctly on AMP pages.

My non-AMP pages make use of image urls that make use of the Amazon image API. Long story short, I display redirected, hotlinked images from Amazon on my pages.

For some reason, this library is incapable of correctly determining the image dimensions. If I use non-redirected image urls, it works fine. I can't just switch to using all non-redirected images, because then I'm not using Amazon's image api anymore. You can't directly hotlink their images, because it's again the ToS and it can get you in trouble.

Because the dimensions can't be determine, AMP4WP displays them in the default dimensions of 1000x400, which are incorrect, ofcourse. This will make images appear stretched and therefore aspect ratio incorrect.

Thankfully, the AMP4WP crew have given me a way to enforce usage of 'fastimage' instead, because they've also included that library in their plugin. This yields much better image results overall, although that plugin sometimes also determines image dimensions incorrectly.

This issue has been nagging me on and off for well over a year now. It comes and goes and is generally very unpredictable. I've used 'fasterimage' in the past few months and got good results. Now all of a sudden it doesn't work anymore, forcing me to switch back to 'fastimage'.

I'd give my third kidney to get this issue out of my hair. 

You know what would fix it?

An option to enforce the full download of an image, to guarantee successful determination of image dimensions. Amazon's image servers are blazing fast and their images aren't that large, anyway.

If this library would support it, and I could get AMP4WP to include the new version *and* let me use a code filter to enforce full image download for dimension determination, then I'm sure my problem would be solved forever.

**Comment by willwashburn** [comment]
Thanks for sharing and for all the detail. Is it possible to share an example image / link that this behavior happens?

In theory, FasterImage _should_ already download all of the image if it can't ever determine any of the flags for the size. I'm guessing it's finding something and it's just the wrong one. I'm not sure forcing the full download would work because those flags would still be wrong. Maybe I'm misunderstanding, though! 

Example would definitely help. 

Thanks and hope we can figure it out!

**Comment by jwbats** [comment]
I can't give out the link to my site publicly, but I suppose I could try to set up a demo site on which this problem occurs. It can be hard to reproduce sometimes, though.

I just found such an incident where it happened for a non-redirected image. This issue just keeps on surprising me.

It is not deterministic. It's not like it's always the same collection of images that get stretched. I can clean cache and clear transients and reload pages and then some other image will be suffering from it. 

Although I must confess that this is currently happening on fastimage, not fasterimage. But then again, fasterimage is currently screwing up almost all images. I feel it might also have something to do with its batch functionality.

I will see if I can set up a site for you that reproduces the issue. I will then give you full access to it.

You got an email somewhere I might use to send you credentials in private?

**Comment by willwashburn** [comment]
Sounds like a hairy issue -- seems strange that redirection would have anything to do with it, unless we're just not able to stream any of the image or it's too many redirects or something like that. 

Are you on twitter? might be easiest to DM me there twitter.com/willwashburn (related: Github needs a DM feature!)

**Comment by jwbats** [comment]
It's very hairy. But at the moment it's very easy to reproduce. You should be able to observe it quite easily once I've given you access to my test site, which is ready for your visit.

I've added you on twitter but can't DM you unless you follow me back (I think).

I won't give out my whole twitter username on here, so check your recent followers for a new follower whose account starts with [redacted] and follow me back.

**Comment by jwbats** [comment]
I've finally had the time to debug why this library fails for my particular situation when it's used in my AMP plugin.

I'm using image urls which are redirected. With this parameter set to false, the image retrieval fails and the program throws an exception saying the stream is too small. That's because the stream is of 0 length when this is set to false.

Once I enabled redirection, I noticed that image sizes were successfully being retrieved. However, there was another bug. The sizes of the images were being mixed up within collections of images. This is because by the sharing of the $stream and $parser variables in multiple requests.

The fix is as follows. In the file FasterImage.php:

1. The 'follow_redirects' parameter in the $options variable must be set to true. 

2. The variable declarations of $stream and $parser are placed at the top of the batch() function. This makes the request_multiple() function overwrite image sizes in multiple, parallel requests. They should be placed within the 'complete' event of the $options variable. This means they need to be taken out of the 'use' statement that follows the function declaration.

3. Optionally, you could update the outdated user agent string to make the reques look more like a modern day browser request.

Would be great if you could make the changes, @willwashburn.

**Comment by willwashburn** [comment]
Thanks @jwbats! I really appreciate you taking the time to look into this and figure out some solutions.

I'll go ahead and add an option to pass through curl parameters so the user can set different settings for redirects or user agents. I believe thats what you mean by 
> 'follow_redirects' parameter in the $options variable must be set to true

I'm assuming I've never had this problem as my default curl settings might be to follow redirects. This solution would also allow you to set the user agent string if you wanted!

I'm having a hard time understanding some of what you meant in your second point. The batch function is intended to be used for multiple, parallel requests and I have some tests in the library _I think_ show that it works correctly 😅. Do you have an example of urls where image sizes are getting mixed up? I'm having trouble recreating that. The way I understood what you said as a solution I think would break how the stream works as it needs a reference to the stream as it writes to it.

Anyways, an example I could throw in the tests would really help me prove the issue and then solve it!

**Comment by willwashburn** [comment]
@jwbats how did you "enable redirection" ? Turns out, this was already set in the latest verson

https://github.com/willwashburn/fasterimage/blob/df6dbe916723478e54c5cb55a7ee55ea3388c146/src/FasterImage/FasterImage.php#L124

**Comment by jwbats** [comment]
I was able to solve all problems in the **FasterImage.php** file, which I'm sure I mentioned in my previous post. The file is small. The follow_redirects option is easy to find in there.

The $stream and $parser variables aren't needed globally in the batch() function. They're needed in the complete() event. That's where I placed them. And that's how I solved the bug of this library mixing up dimensions within the same batch of parallel retrievals. Right now, you've got multiple requests working on the same variables. It's no wonder it yields incorrect results.

I'll see if I can put together an example for you.

**Comment by willwashburn** [comment]
> I was able to solve all problems in the FasterImage.php file, which I'm sure I mentioned in my previous post. The file is small. The follow_redirects option is easy to find in there.

Perhaps you're using an outdated version? If you look at my previous comment I've linked directly to where it is set to true.

> The $stream and $parser variables aren't needed globally in the batch() function. They're needed in the complete() event. That's where I placed them. And that's how I solved the bug of this library mixing up dimensions within the same batch of parallel retrievals. Right now, you've got multiple requests working on the same variables. It's no wonder it yields incorrect results.

I'm looking forward to an example here because I haven't seen this anywhere else. The way you're describing the variable scoping doesn't make sense to me -- those are separate curl handles and the $stream and $parser variables are local to that handle. They need to be shared with the WRITE_FUNCTION since that's how to keep track of the whole stream. I'm actually not even sure what complete event you're talking about, but regardless -- happy this library was helpful to you and you were able to figure it out.

**Comment by jwbats** [comment]
Oh, I see where the confusion comes from.

I am using the FasterImage version that is used in the Accelerated Mobile Pages plugin I'm using. It must be much older than your latest version, since the FasterImage.php files differ greatly from each other.

Anyway, I've sent screenshots to your twitter private chat, since I don't want to publicly show my SEO content.

**Comment by jwbats** [comment]
Both my version as well as the one you linked to show 0.01 above the FasterImage class.

The files are quite different, however. It could also be that the AMP plugin guys have completely rewritten your source, in which case you certainly aren't to blame.

Did your source ever look anything like this?

```
public function batch(array $urls)
    {
        $results          = [];
        $request          = array();
        foreach ( array_values($urls) as $count => $uri ) {
            $results[$uri] = array();
            $request[$uri] = array(
                'url' =>  $uri,
                'type' => 'GET',
            );
        }
        $options= array(
                    'timeout'=>$this->timeout,
                    'connect_timeout'=>$this->timeout,
                    'useragent'=>'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36',
                    'verify'=> 1,
                    'verifyname'=>1,
                    'follow_redirects'=>true,
                    'complete'=> function($response, $url) use(&$results){
                        $stream = new Stream();
                        $parser = new ImageParser($stream);
                        $results[$url]['rounds'] = 0;
                        $results[$url]['bytes']  = 0;
                        $results[$url]['size']   = 'failed';
                        if( is_a( $response, 'Requests_Response' ) ){
                            $str = $response->body;
                            $results[$url]['bytes'] += strlen($str);
                            $results[$url]['rounds']++;
                            $stream->write($str);
                            try {
								// store the type in the result array by looking at the bits
								 $results[$url]['type'] = $parser->parseType();
								 $results[$url]['size'] = $parser->parseSize() ?: 'failed';
							}
							catch (StreamBufferTooSmallException $e) {
								$results[$url]['size'] = 'failed';
								return strlen($str);
							}
							catch (InvalidImageException $e) {
								$results[$url]['size'] = 'invalid';
								return -1;
							}
							return -1;
                        }
                    }
        );

        $responseResults = \Requests::request_multiple($request , $options);
        return $results;
    }
```

Because this is what I've been having my problems with.

**Comment by willwashburn** [comment]
Ahhhhh, I see -- no I've never seen this. It's probable they copied over some stuff to make it work in their framework but crossed some wires.

I wonder why they weren't able to use the library directly?

**Comment by jwbats** [comment]
I also have no idea. But it is open source and they had every right to do so. I should've compared files earlier. Unfortunately, I got so caught up in this month long headache that I didn't even consider that option.

Looks like my beef is entirely with them and not with you at all. Sorry to have wasted your time.

**Comment by willwashburn** [comment]
All good -- good luck with things in the future!
